---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "gomod"
    directories:
    - "/.build"
    - "/demo"
    - "/duplicati/wrapper"
    schedule:
      interval: daily
