---
name: echocat's Demo
version: 0.0.2
slug: demo
description: Demonstrates a very basic addon for Home Assistant
url: https://github.com/echocat/hassos-addons/demo
#image: local/demo
startup: application
ingress: true
ingress_port: 8300
panel_icon: mdi:web
panel_title: Demo
panel_admin: false
boot: auto
host_network: false
privileged: []
options: {}
schema": {}
arch:
  - amd64
  - aarch64
  - armv7
